name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v4

    - name: Install dependencies
      working-directory: my-web-app
      run: npm install

    - name: Build
      working-directory: my-web-app
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./build
